version: "3" 
services:
  react:
    image: reactjsga
    container_name : reactjs
    ports:
      - "3000:3000" 
    depends_on:
      - node 
    networks:
      - ga 

  node:
    image: node-ga-14v1
    container_name : nodejs
    ports:
      - "3001:3001" 
    depends_on:
      - db 
    networks:  
      - ga

  db:
    image: mariadb:10.4
    container_name : mariadbteste
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
    - ./storage/db:/var/lib/mysql:rw
    - "./mysql/:/docker-entrypoint-initdb.d/:rw"
    ports:
    - 3306:3306
    networks:
    - ga

networks:
  ga:
    driver: bridge

